### ISSUE TITLE
the following says 1 file available but download failed. can u meet with me for 5 min and hepl me out please?

### ISSUE THREAD

**Issue by kaushikCanada** [ghiggi/gpm_api#38]
pm_api.define_configs(username_pps=username,
                       password_pps=password,
                       username_earthdata = username,
                       password_earthdata= password,
                       gpm_base_dir=gpm_base_dir)

# You can check that the config file has been correctly created with:
configs = gpm_api.read_configs()
print(configs)

product = "IMERG-ER"
product_type = "NRT"
version = 6

start_time = datetime.datetime(2020,7, 22, 0, 1, 11)
end_time = datetime.datetime(2020,7, 22, 0, 23, 5)

gpm_api.download(product=product,
                 product_type=product_type,
                 version=version,
                 n_threads=2,
                 start_time=start_time,
                 end_time=end_time,
                storage ="ges_disc",
                 progress_bar=True,
                 force_download=False,
                verbose=True)

**Comment by ghiggi** [comment]
Seeing your code your are aiming to download a single IMERG file the 2020-7-22 between 00:00 and 00:30. 
I tried on my side and the software does the expected job. 

Can you try to switch the `storage` to "pps" and check if the download works?
I guess there is something missing in your EarthData Account. Please read carefully what to do in the [Quick Start documentation](https://gpm-api.readthedocs.io/en/latest/03_quickstart.html) and tell me back if the problem is resolved !
